<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_EditGist</name>
   <tag></tag>
   <elementGuidId>0b9916de-a88d-4cb7-99fc-fdb1071dc4be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;gist-pjax-container&quot;]/div[1]/div/div[1]/ul/li[1]/a/svg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;gist-pjax-container&quot;]/div[1]/div/div[1]/ul/li[1]/a/svg</value>
   </webElementXpaths>
</WebElementEntity>
