<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_DeleteGist</name>
   <tag></tag>
   <elementGuidId>48a96ca6-10a5-49bb-97cc-aa44679fc475</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;gist-pjax-container&quot;]/div[1]/div/div[1]/ul/li[2]/form/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;gist-pjax-container&quot;]/div[1]/div/div[1]/ul/li[2]/form/button</value>
   </webElementXpaths>
</WebElementEntity>
